### ISSUE TITLE
Rename bias into influence

### ISSUE THREAD

**Issue by Vayel** [MaxHalford/ethik#93]

**Comment by Vayel** [comment]
@MaxHalford do you remember why we replaced `explain_predictions()` with `explain_bias()`?

In theory, it should be `explain_influence_on_predictions/performance()` but it's a bit long. Maybe we can just use `explain_predictions()`? But since we gave up this name, I guess we had a good reason.

**Comment by Vayel** [comment]
I like it as well, but it doesn't tell use what the influence is on. Would you call the methods `explain_influence` and `explain_performance`?

**Comment by MaxHalford** [comment]
Maybe it's just me but I find that `explain_influence` is enough informative. I think it's pretty obvious that the influence we're hinting at is between the features and the target, which is why users are using the package in the first place. This is Python, not C# :). `explain_performance` seems good to me.

**Comment by Vayel** [comment]
What I mean is that `explain_performance` is also the explanation of an influence (on the performance). But I'm ok with using `explain_influence` for the predictions.

**Comment by MaxHalford** [comment]
Ah, I see what you mean... I'll have a think about it.
