### ISSUE TITLE
Check if the distribution is a dirac

### ISSUE THREAD

**Issue by Vayel** [MaxHalford/ethik#94]

**Comment by Vayel** [comment]
@MaxHalford for `ImageExplainer`, it's always the case:

![image](https://user-images.githubusercontent.com/6124369/66636927-620b8780-ec12-11e9-8738-906f23571942.png)

Both quantiles are equal to zero.

Is it expected?

**Comment by MaxHalford** [comment]
Do you mean that `bias_low == bias_high` even when `n_samples > 1`?

**Comment by Vayel** [comment]
I mean that `bias(tau = -1) == bias(tau = 1)`. But it's because I only checked black pixels...

![image](https://user-images.githubusercontent.com/6124369/66638060-8ff1cb80-ec14-11e9-86fb-236447f70772.png)

It still raises the question of raising a warning when we have a dirac distribution (which is the case for pixels that are always black across samples).

**Comment by MaxHalford** [comment]
Yeah indeed, there is no variation whatsoever if the pixels are black.

**Comment by Vayel** [comment]
To avoid having the warning for images, we can just have it for local bias. Actually it makes sense because if the whole dataset is a dirac, we can consider it's the user's mistake. But for local bias, we sample a subset of the dataset so we need to make sure we do it properly.

**Comment by MaxHalford** [comment]
We should issue a warning when a variable has only one unique value, because typically that is an edge-case. However, for images this case arises quite regularly, and so we shouldn't issue a warning.

It seems that we can catch warnings in Python and suppress them. See [this StackOverflow post](https://stackoverflow.com/questions/14463277/how-to-disable-python-warnings). I think that we can use the `category` parameter in the [warnings.simplefilter](https://stackoverflow.com/questions/14463277/how-to-disable-python-warnings).
